CONTAINER = {
    "name": "1_get_3_4",
    "agents": [{'id': 1,
           'name': 'agent 1',
           'pos': [-500, -500],
           'attention': 0.0,
           'rotate': 0.0,
           'desire': {'active': 1, 'social': 0, 'helpful': 0},
           'intent': {'ind': ['get', 3, None], 'soc': None, 'comm': None, 'ref': None, 'type':"HILU"}},
          {'id': 2,
           'name': 'agent 2',
           'pos': [400, -300],
           'attention': -0.9,
           'rotate': -0.9,
           'belief_obj_ids': [3, 4],
           'desire': {'active': 1, 'social': 0, 'helpful': 1},
           'intent': {'ind': ['explore'], 'soc': None, 'comm': None, 'ref': None, 'type':"LILU"}
           }],
    "objects": [{'id': 3,
         'name': 'cup',
         'color': [0.85, 0.15, 0.35],
         'size': [64, 46],
         'pos': [0, 300],
         'rotate': 0.5,
         'is_game': True,
         'being_contained': [4]},
        {'id': 4,
         'name': 'box',
         'color': [1, 1, 240],
         'size': [79, 101],
         'pos': [0, 300],
         'rotate': 0.5,
         'is_container': True,
         'open': False,
         'containing': [3]}
        ],
    "landmarks": None
}